# yamllint disable rule:line-length rule:comments-indentation
name: compile-hello-world  # yamllint disable-line rule:document-start

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "test*"  # for testing
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.5.1]
        # os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Determine tag"
        run: |
          # echo "RELEASE_TAG=${{ GITHUB_REF#refs/tags/ }}"
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV"
          echo ${{ env.RELEASE_TAG }}
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          # echo 1: ${{ github.ref_name }} or 2:  $GITHUB_REF_NAME or 3: ${{env.GITHUB_REF_NAME}}
      - name: "Use RELEASE_TAG"
        run: |
          echo "The release tag is $RELEASE_TAG"
