# yamllint disable rule:line-length rule:comments-indentation
name: compile-hello-world  # yamllint disable-line rule:document-start

          # echo "RELEASE_TAG=${{ GITHUB_REF#refs/tags/ }}"
          # echo "RELEASE_TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV"
          # echo ${{ env.RELEASE_TAG }}
          # echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          # echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          # echo 1: ${{ github.ref_name }} or 2:  $GITHUB_REF_NAME or 3: ${{env.GITHUB_REF_NAME}}

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "test*"  # for testing
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.5.1]
        # os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: "Determine tag"
        run: |
          echo Add other actions to build
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: "Use RELEASE_TAG"
        run: |
          echo Use RELEASE_TAG ${{  github.ref_name }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      # not necessary if using Nuitka/Nuitka-Action@main
      - name: Install dependencies
        run: poetry install
      _ name: test gh
        run: gh --version
