# yamllint disable rule:line-length rule:comments-indentation
name: compile-hello-world  # yamllint disable-line rule:document-start

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "test*"  # for testing
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.5.1]
        # os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: "Determine tag"
        run: |
          echo Add other actions to build

      - name: "Use RELEASE_TAG"
        run: |
          echo "The release tag is $RELEASE_TAG"
