name: my workflow
on: push

jobs:
  job1:
    runs-on: windows-latest
    defaults:
      run:
        # shell: pwsh
        shell: cmd
    steps:
      - name: Hello world
        run: |
          REM write-output "Hello World"
          echo "Hello World"
          echo 1 %GITHUB_WORKSPACE 2 %GITHUB_WORKSPACE%