name: my workflow
on: push

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.5.1]
        # os: [ubuntu-20.04, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: windows-latest
    defaults:
      run:
        # shell: pwsh
        shell: cmd
    steps:
      - name: Hello world
        run: |
          REM write-output "Hello World"
          echo "Hello World"
          echo 1 $GITHUB_WORKSPACE 2 ${{ github.workspace }}
          echo matrix.os: ${{ matrix.os }}
